In [ ]:
## import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import os
import collections
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
!pip3 install openpyxl
Requirement already satisfied: openpyxl in c:\users\vicky reddy\anaconda3\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\vicky reddy\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
# loading dataset
df=pd.read_csv('weather.csv')
df.head()
366 Days	MinTemp	MaxTemp	Rainfall	Evaporation	Sunshine	WindGustDir	WindGustSpeed	WindDir9am	WindDir3pm	...	Humidity3pm	Pressure9am	Pressure3pm	Cloud9am	Cloud3pm	Temp9am	Temp3pm	RainToday	RISK_MM	RainTomorrow
0	1	8.0	24.3	0.0	3.4	6.3	NW	30.0	SW	NW	...	29	1019.7	1015.0	7	7	14.4	23.6	No	3.6	Yes
1	2	14.0	26.9	3.6	4.4	9.7	ENE	39.0	E	W	...	36	1012.4	1008.4	5	3	17.5	25.7	Yes	3.6	Yes
2	3	13.7	23.4	3.6	5.8	3.3	NW	85.0	N	NNE	...	69	1009.5	1007.2	8	7	15.4	20.2	Yes	39.8	Yes
3	4	13.3	15.5	39.8	7.2	9.1	NW	54.0	WNW	W	...	56	1005.5	1007.0	2	7	13.5	14.1	Yes	2.8	Yes
4	5	7.6	16.1	2.8	5.6	10.6	SSE	50.0	SSE	ESE	...	49	1018.3	1018.5	7	7	11.1	15.4	Yes	0.0	No
5 rows Ã— 23 columns

dfa=pd.read_csv('rainfall in india 1901-2015.csv')
dfa.head()
SUBDIVISION	YEAR	JAN	FEB	MAR	APR	MAY	JUN	JUL	AUG	SEP	OCT	NOV	DEC	ANNUAL	Jan-Feb	Mar-May	Jun-Sep	Oct-Dec
0	ANDAMAN & NICOBAR ISLANDS	1901	49.2	87.1	29.2	2.3	528.8	517.5	365.1	481.1	332.6	388.5	558.2	33.6	3373.2	136.3	560.3	1696.3	980.3
1	ANDAMAN & NICOBAR ISLANDS	1902	0.0	159.8	12.2	0.0	446.1	537.1	228.9	753.7	666.2	197.2	359.0	160.5	3520.7	159.8	458.3	2185.9	716.7
2	ANDAMAN & NICOBAR ISLANDS	1903	12.7	144.0	0.0	1.0	235.1	479.9	728.4	326.7	339.0	181.2	284.4	225.0	2957.4	156.7	236.1	1874.0	690.6
3	ANDAMAN & NICOBAR ISLANDS	1904	9.4	14.7	0.0	202.4	304.5	495.1	502.0	160.1	820.4	222.2	308.7	40.1	3079.6	24.1	506.9	1977.6	571.0
4	ANDAMAN & NICOBAR ISLANDS	1905	1.3	0.0	3.3	26.9	279.5	628.7	368.7	330.5	297.0	260.7	25.4	344.7	2566.7	1.3	309.7	1624.9	630.8
dfb=pd.read_csv('District wise rainfall normal.csv')
dfb.head()
STATE_UT_NAME	DISTRICT	JAN	FEB	MAR	APR	MAY	JUN	JUL	AUG	SEP	OCT	NOV	DEC	ANNUAL	Jan-Feb	Mar-May	Jun-Sep	Oct-Dec
0	ANDAMAN And NICOBAR ISLANDS	NICOBAR	107.3	57.9	65.2	117.0	358.5	295.5	285.0	271.9	354.8	326.0	315.2	250.9	2805.2	165.2	540.7	1207.2	892.1
1	ANDAMAN And NICOBAR ISLANDS	SOUTH ANDAMAN	43.7	26.0	18.6	90.5	374.4	457.2	421.3	423.1	455.6	301.2	275.8	128.3	3015.7	69.7	483.5	1757.2	705.3
2	ANDAMAN And NICOBAR ISLANDS	N & M ANDAMAN	32.7	15.9	8.6	53.4	343.6	503.3	465.4	460.9	454.8	276.1	198.6	100.0	2913.3	48.6	405.6	1884.4	574.7
3	ARUNACHAL PRADESH	LOHIT	42.2	80.8	176.4	358.5	306.4	447.0	660.1	427.8	313.6	167.1	34.1	29.8	3043.8	123.0	841.3	1848.5	231.0
4	ARUNACHAL PRADESH	EAST SIANG	33.3	79.5	105.9	216.5	323.0	738.3	990.9	711.2	568.0	206.9	29.5	31.7	4034.7	112.8	645.4	3008.4	268.1
df.shape
(366, 23)
dfa.shape
(4116, 19)
dfb.shape
(641, 19)
df.info()
RangeIndex: 366 entries, 0 to 365
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   366 Days       366 non-null    int64  
 1   MinTemp        366 non-null    float64
 2   MaxTemp        366 non-null    float64
 3   Rainfall       366 non-null    float64
 4   Evaporation    366 non-null    float64
 5   Sunshine       363 non-null    float64
 6   WindGustDir    363 non-null    object 
 7   WindGustSpeed  364 non-null    float64
 8   WindDir9am     335 non-null    object 
 9   WindDir3pm     365 non-null    object 
 10  WindSpeed9am   359 non-null    float64
 11  WindSpeed3pm   366 non-null    int64  
 12  Humidity9am    366 non-null    int64  
 13  Humidity3pm    366 non-null    int64  
 14  Pressure9am    366 non-null    float64
 15  Pressure3pm    366 non-null    float64
 16  Cloud9am       366 non-null    int64  
 17  Cloud3pm       366 non-null    int64  
 18  Temp9am        366 non-null    float64
 19  Temp3pm        366 non-null    float64
 20  RainToday      366 non-null    object 
 21  RISK_MM        366 non-null    float64
 22  RainTomorrow   366 non-null    object 
dtypes: float64(12), int64(6), object(5)
memory usage: 65.9+ KB
dfa.info()
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SUBDIVISION  4116 non-null   object 
 1   YEAR         4116 non-null   int64  
 2   JAN          4112 non-null   float64
 3   FEB          4113 non-null   float64
 4   MAR          4110 non-null   float64
 5   APR          4112 non-null   float64
 6   MAY          4113 non-null   float64
 7   JUN          4111 non-null   float64
 8   JUL          4109 non-null   float64
 9   AUG          4112 non-null   float64
 10  SEP          4110 non-null   float64
 11  OCT          4109 non-null   float64
 12  NOV          4105 non-null   float64
 13  DEC          4106 non-null   float64
 14  ANNUAL       4090 non-null   float64
 15  Jan-Feb      4110 non-null   float64
 16  Mar-May      4107 non-null   float64
 17  Jun-Sep      4106 non-null   float64
 18  Oct-Dec      4103 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB
dfb.info()
RangeIndex: 641 entries, 0 to 640
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   STATE_UT_NAME  641 non-null    object 
 1   DISTRICT       641 non-null    object 
 2   JAN            641 non-null    float64
 3   FEB            641 non-null    float64
 4   MAR            641 non-null    float64
 5   APR            641 non-null    float64
 6   MAY            641 non-null    float64
 7   JUN            641 non-null    float64
 8   JUL            641 non-null    float64
 9   AUG            641 non-null    float64
 10  SEP            641 non-null    float64
 11  OCT            641 non-null    float64
 12  NOV            641 non-null    float64
 13  DEC            641 non-null    float64
 14  ANNUAL         641 non-null    float64
 15  Jan-Feb        641 non-null    float64
 16  Mar-May        641 non-null    float64
 17  Jun-Sep        641 non-null    float64
 18  Oct-Dec        641 non-null    float64
dtypes: float64(17), object(2)
memory usage: 95.3+ KB
df.RainTomorrow.value_counts()
No     300
Yes     66
Name: RainTomorrow, dtype: int64
df.RainToday.value_counts()
No     300
Yes     66
Name: RainToday, dtype: int64
dfa.SUBDIVISION.value_counts()
WEST MADHYA PRADESH                   115
EAST RAJASTHAN                        115
COASTAL KARNATAKA                     115
TAMIL NADU                            115
RAYALSEEMA                            115
TELANGANA                             115
COASTAL ANDHRA PRADESH                115
CHHATTISGARH                          115
VIDARBHA                              115
MATATHWADA                            115
MADHYA MAHARASHTRA                    115
KONKAN & GOA                          115
SAURASHTRA & KUTCH                    115
GUJARAT REGION                        115
EAST MADHYA PRADESH                   115
KERALA                                115
WEST RAJASTHAN                        115
SOUTH INTERIOR KARNATAKA              115
JAMMU & KASHMIR                       115
HIMACHAL PRADESH                      115
PUNJAB                                115
HARYANA DELHI & CHANDIGARH            115
UTTARAKHAND                           115
WEST UTTAR PRADESH                    115
EAST UTTAR PRADESH                    115
BIHAR                                 115
JHARKHAND                             115
ORISSA                                115
GANGETIC WEST BENGAL                  115
SUB HIMALAYAN WEST BENGAL & SIKKIM    115
NAGA MANI MIZO TRIPURA                115
ASSAM & MEGHALAYA                     115
NORTH INTERIOR KARNATAKA              115
LAKSHADWEEP                           114
ANDAMAN & NICOBAR ISLANDS             110
ARUNACHAL PRADESH                      97
Name: SUBDIVISION, dtype: int64
dfb.DISTRICT.value_counts()
BIJAPUR        2
BILASPUR       2
AURANGABAD     2
HAMIRPUR       2
NICOBAR        1
              ..
GONDA          1
GORAKHPUR      1
HARDOI         1
JAUNPUR        1
LAKSHADWEEP    1
Name: DISTRICT, Length: 637, dtype: int64
df.describe()
366 Days	MinTemp	MaxTemp	Rainfall	Evaporation	Sunshine	WindGustSpeed	WindSpeed9am	WindSpeed3pm	Humidity9am	Humidity3pm	Pressure9am	Pressure3pm	Cloud9am	Cloud3pm	Temp9am	Temp3pm	RISK_MM
count	366.000000	366.000000	366.000000	366.000000	366.000000	363.000000	364.000000	359.000000	366.000000	366.000000	366.000000	366.000000	366.000000	366.000000	366.000000	366.000000	366.000000	366.000000
mean	183.500000	7.265574	20.550273	1.428415	4.521858	7.909366	39.840659	9.651811	17.986339	72.035519	44.519126	1019.709016	1016.810383	3.890710	4.024590	12.358470	19.230874	1.428415
std	105.799338	6.025800	6.690516	4.225800	2.669383	3.481517	13.059807	7.951929	8.856997	13.137058	16.850947	6.686212	6.469422	2.956131	2.666268	5.630832	6.640346	4.225800
min	1.000000	-5.300000	7.600000	0.000000	0.200000	0.000000	13.000000	0.000000	0.000000	36.000000	13.000000	996.500000	996.800000	0.000000	0.000000	0.100000	5.100000	0.000000
25%	92.250000	2.300000	15.025000	0.000000	2.200000	5.950000	31.000000	6.000000	11.000000	64.000000	32.250000	1015.350000	1012.800000	1.000000	1.000000	7.625000	14.150000	0.000000
50%	183.500000	7.450000	19.650000	0.000000	4.200000	8.600000	39.000000	7.000000	17.000000	72.000000	43.000000	1020.150000	1017.400000	3.500000	4.000000	12.550000	18.550000	0.000000
75%	274.750000	12.500000	25.500000	0.200000	6.400000	10.500000	46.000000	13.000000	24.000000	81.000000	55.000000	1024.475000	1021.475000	7.000000	7.000000	17.000000	24.000000	0.200000
max	366.000000	20.900000	35.800000	39.800000	13.800000	13.600000	98.000000	41.000000	52.000000	99.000000	96.000000	1035.700000	1033.200000	8.000000	8.000000	24.700000	34.500000	39.800000
dfa.describe()
YEAR	JAN	FEB	MAR	APR	MAY	JUN	JUL	AUG	SEP	OCT	NOV	DEC	ANNUAL	Jan-Feb	Mar-May	Jun-Sep	Oct-Dec
count	4116.000000	4112.000000	4113.000000	4110.000000	4112.000000	4113.000000	4111.000000	4109.000000	4112.000000	4110.000000	4109.000000	4105.000000	4106.000000	4090.000000	4110.000000	4107.000000	4106.000000	4103.000000
mean	1958.218659	18.957320	21.805325	27.359197	43.127432	85.745417	230.234444	347.214334	290.263497	197.361922	95.507009	39.866163	18.870580	1411.008900	40.747786	155.901753	1064.724769	154.100487
std	33.140898	33.585371	35.909488	46.959424	67.831168	123.234904	234.710758	269.539667	188.770477	135.408345	99.519134	68.685410	42.369611	903.846565	59.308277	201.316965	707.741531	166.942660
min	1901.000000	0.000000	0.000000	0.000000	0.000000	0.000000	0.400000	0.000000	0.000000	0.100000	0.000000	0.000000	0.000000	62.300000	0.000000	0.000000	57.400000	0.000000
25%	1930.000000	0.600000	0.600000	1.000000	3.000000	8.600000	70.350000	175.600000	155.975000	100.525000	14.600000	0.700000	0.100000	804.500000	4.100000	24.050000	573.850000	34.200000
50%	1958.000000	6.000000	6.700000	7.800000	15.700000	36.600000	138.700000	284.800000	259.400000	173.900000	65.200000	9.500000	3.000000	1121.300000	19.200000	74.800000	881.100000	98.200000
75%	1987.000000	22.200000	26.800000	31.300000	49.950000	97.200000	305.150000	418.400000	377.800000	265.800000	148.400000	46.100000	17.500000	1644.775000	50.375000	196.950000	1288.175000	213.500000
max	2015.000000	583.700000	403.500000	605.600000	595.100000	1168.600000	1609.900000	2362.800000	1664.600000	1222.000000	948.300000	648.900000	617.500000	6331.100000	699.500000	1745.800000	4536.900000	1252.500000
dfb.describe()
JAN	FEB	MAR	APR	MAY	JUN	JUL	AUG	SEP	OCT	NOV	DEC	ANNUAL	Jan-Feb	Mar-May	Jun-Sep	Oct-Dec
count	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.000000	641.00000	641.000000
mean	18.355070	20.984399	30.034789	45.543214	81.535101	196.007332	326.033697	291.152262	194.609048	90.446334	34.117473	18.150858	1346.969579	39.339470	157.113105	1007.80234	142.714665
std	21.082806	27.729596	45.451082	71.556279	111.960390	196.556284	221.364643	152.647325	99.830540	74.990685	59.371274	32.711009	838.878874	47.212773	213.445888	629.33261	148.951752
min	0.000000	0.000000	0.000000	0.000000	0.900000	3.800000	11.600000	14.100000	8.600000	3.100000	1.200000	0.000000	94.600000	0.000000	1.500000	39.60000	5.600000
25%	6.900000	7.000000	7.000000	5.000000	12.100000	68.800000	206.400000	194.600000	128.800000	34.300000	6.600000	5.300000	830.400000	14.700000	27.800000	625.40000	51.600000
50%	13.300000	12.300000	12.700000	15.100000	33.900000	131.900000	293.700000	284.800000	181.300000	62.600000	12.900000	7.900000	1116.200000	27.700000	67.200000	896.60000	86.700000
75%	19.200000	24.100000	33.200000	48.300000	91.900000	226.600000	374.800000	358.100000	234.100000	130.200000	32.300000	14.900000	1530.900000	41.100000	172.400000	1193.80000	175.200000
max	144.500000	229.600000	367.900000	554.400000	733.700000	1476.200000	1820.900000	1522.100000	826.300000	517.700000	475.100000	297.700000	7229.300000	335.300000	1256.500000	5228.00000	1048.500000
# univariate analysis.
sns.distplot(df.ANNUAL)
YEAR	JAN	FEB	MAR	APR	MAY	JUN	JUL	AUG	SEP	OCT	NOV	DEC	ANNUAL	Jan-Feb	Mar-May	Jun-Sep	Oct-Dec
count	4116.000000	4112.000000	4113.000000	4110.000000	4112.000000	4113.000000	4111.000000	4109.000000	4112.000000	4110.000000	4109.000000	4105.000000	4106.000000	4090.000000	4110.000000	4107.000000	4106.000000	4103.000000
mean	1958.218659	18.957320	21.805325	27.359197	43.127432	85.745417	230.234444	347.214334	290.263497	197.361922	95.507009	39.866163	18.870580	1411.008900	40.747786	155.901753	1064.724769	154.100487
std	33.140898	33.585371	35.909488	46.959424	67.831168	123.234904	234.710758	269.539667	188.770477	135.408345	99.519134	68.685410	42.369611	903.846565	59.308277	201.316965	707.741531	166.942660
min	1901.000000	0.000000	0.000000	0.000000	0.000000	0.000000	0.400000	0.000000	0.000000	0.100000	0.000000	0.000000	0.000000	62.300000	0.000000	0.000000	57.400000	0.000000
25%	1930.000000	0.600000	0.600000	1.000000	3.000000	8.600000	70.350000	175.600000	155.975000	100.525000	14.600000	0.700000	0.100000	804.500000	4.100000	24.050000	573.850000	34.200000
50%	1958.000000	6.000000	6.700000	7.800000	15.700000	36.600000	138.700000	284.800000	259.400000	173.900000	65.200000	9.500000	3.000000	1121.300000	19.200000	74.800000	881.100000	98.200000
75%	1987.000000	22.200000	26.800000	31.300000	49.950000	97.200000	305.150000	418.400000	377.800000	265.800000	148.400000	46.100000	17.500000	1644.775000	50.375000	196.950000	1288.175000	213.500000
max	2015.000000	583.700000	403.500000	605.600000	595.100000	1168.600000	1609.900000	2362.800000	1664.600000	1222.000000	948.300000	648.900000	617.500000	6331.100000	699.500000	1745.800000	4536.900000	1252.500000
# univariate analysis.
sns.distplot(df.Rainfall)

 # bivariate analysis.
sns.lineplot(dfa.YEAR,dfa.ANNUAL)

plt.pie(df.RainToday.value_counts(),[0.2,0],colors=['green','red'],labels=['No','Yes'],autopct="%1.1f%%")
plt.title('RainToday')
plt.show()

sns.barplot(df.WindGustDir.value_counts().index, df.WindGustDir.value_counts())

sns.pairplot(dfa)

sns.pairplot(df)

sns.pairplot(df)

df.corr()
366 Days	MinTemp	MaxTemp	Rainfall	Evaporation	Sunshine	WindGustSpeed	WindSpeed9am	WindSpeed3pm	Humidity9am	Humidity3pm	Pressure9am	Pressure3pm	Cloud9am	Cloud3pm	Temp9am	Temp3pm	RISK_MM
366 Days	1.000000	-0.655682	-0.540103	-0.147967	-0.350377	-0.035487	0.079834	0.075023	0.280186	-0.029452	-0.042443	0.326285	0.319532	-0.133501	-0.152711	-0.583006	-0.521359	-0.151170
MinTemp	-0.655682	1.000000	0.752471	0.201939	0.649930	0.035711	0.218020	0.127542	-0.065922	-0.207897	-0.040709	-0.501707	-0.498007	0.215776	0.118397	0.916745	0.722730	0.218551
MaxTemp	-0.540103	0.752471	1.000000	-0.073560	0.690026	0.452064	0.109672	-0.216814	-0.167873	-0.359602	-0.533327	-0.290883	-0.379394	-0.175730	-0.135991	0.870604	0.989261	0.027557
Rainfall	-0.147967	0.201939	-0.073560	1.000000	-0.007293	-0.150990	0.096190	0.219637	0.056008	0.150109	0.289013	-0.331581	-0.250218	0.180046	0.127792	0.077299	-0.087493	0.089860
Evaporation	-0.350377	0.649930	0.690026	-0.007293	1.000000	0.318025	0.288477	0.068929	0.048601	-0.519587	-0.391780	-0.381906	-0.391093	-0.106007	-0.100045	0.707676	0.671632	0.076762
Sunshine	-0.035487	0.035711	0.452064	-0.150990	0.318025	1.000000	0.095843	-0.064522	0.072573	-0.499017	-0.759429	0.006276	-0.036201	-0.681092	-0.661131	0.219509	0.470447	-0.378823
WindGustSpeed	0.079834	0.218020	0.109672	0.096190	0.288477	0.095843	1.000000	0.527653	0.693945	-0.349793	-0.069439	-0.540180	-0.526885	-0.012666	0.050230	0.256223	0.072501	0.251991
WindSpeed9am	0.075023	0.127542	-0.216814	0.219637	0.068929	-0.064522	0.527653	1.000000	0.472966	-0.270623	0.146657	-0.356332	-0.247952	0.101842	-0.022471	0.064074	-0.235186	0.039091
WindSpeed3pm	0.280186	-0.065922	-0.167873	0.056008	0.048601	0.072573	0.693945	0.472966	1.000000	-0.266092	-0.026368	-0.359800	-0.337325	-0.026426	0.007207	-0.017766	-0.187570	-0.009447
Humidity9am	-0.029452	-0.207897	-0.359602	0.150109	-0.519587	-0.499017	-0.349793	-0.270623	-0.266092	1.000000	0.546718	0.135727	0.134420	0.392842	0.271938	-0.436551	-0.355119	0.165931
Humidity3pm	-0.042443	-0.040709	-0.533327	0.289013	-0.391780	-0.759429	-0.069439	0.146657	-0.026368	0.546718	1.000000	-0.087946	-0.010052	0.551633	0.510108	-0.255681	-0.581676	0.358752
Pressure9am	0.326285	-0.501707	-0.290883	-0.331581	-0.381906	0.006276	-0.540180	-0.356332	-0.359800	0.135727	-0.087946	1.000000	0.967895	-0.157553	-0.141000	-0.460418	-0.253674	-0.290584
Pressure3pm	0.319532	-0.498007	-0.379394	-0.250218	-0.391093	-0.036201	-0.526885	-0.247952	-0.337325	0.134420	-0.010052	0.967895	1.000000	-0.128944	-0.143837	-0.492636	-0.345485	-0.311421
Cloud9am	-0.133501	0.215776	-0.175730	0.180046	-0.106007	-0.681092	-0.012666	0.101842	-0.026426	0.392842	0.551633	-0.157553	-0.128944	1.000000	0.525218	0.021041	-0.202344	0.273914
Cloud3pm	-0.152711	0.118397	-0.135991	0.127792	-0.100045	-0.661131	0.050230	-0.022471	0.007207	0.271938	0.510108	-0.141000	-0.143837	0.525218	1.000000	0.040945	-0.172814	0.326455
Temp9am	-0.583006	0.916745	0.870604	0.077299	0.707676	0.219509	0.256223	0.064074	-0.017766	-0.436551	-0.255681	-0.460418	-0.492636	0.021041	0.040945	1.000000	0.844406	0.164842
Temp3pm	-0.521359	0.722730	0.989261	-0.087493	0.671632	0.470447	0.072501	-0.235186	-0.187570	-0.355119	-0.581676	-0.253674	-0.345485	-0.202344	-0.172814	0.844406	1.000000	-0.005825
RISK_MM	-0.151170	0.218551	0.027557	0.089860	0.076762	-0.378823	0.251991	0.039091	-0.009447	0.165931	0.358752	-0.290584	-0.311421	0.273914	0.326455	0.164842	-0.005825	1.000000
dfa.corr()
YEAR	JAN	FEB	MAR	APR	MAY	JUN	JUL	AUG	SEP	OCT	NOV	DEC	ANNUAL	Jan-Feb	Mar-May	Jun-Sep	Oct-Dec
YEAR	1.000000	-0.056235	-0.022144	0.020338	0.008007	0.003594	-0.013594	-0.016240	0.006442	-0.006670	0.002406	-0.018776	-0.019139	-0.008044	-0.044653	0.010637	-0.009418	-0.010155
JAN	-0.056235	1.000000	0.456183	0.398502	0.209302	0.129622	-0.033725	-0.051642	0.011952	0.024289	0.012374	0.067281	0.219701	0.105696	0.842390	0.242256	-0.022748	0.090932
FEB	-0.022144	0.456183	1.000000	0.579819	0.367114	0.203062	0.033703	0.016235	0.072159	0.080148	-0.004581	-0.023413	0.132570	0.181563	0.863815	0.382620	0.051066	0.021878
MAR	0.020338	0.398502	0.579819	1.000000	0.556856	0.362815	0.165857	0.097334	0.135071	0.178904	0.086187	0.008814	0.136328	0.322199	0.576366	0.642294	0.162055	0.090108
APR	0.008007	0.209302	0.367114	0.556856	1.000000	0.650595	0.457091	0.268097	0.256168	0.382525	0.368886	0.165642	0.132892	0.577573	0.340841	0.864172	0.394859	0.321407
MAY	0.003594	0.129622	0.203062	0.362815	0.650595	1.000000	0.567618	0.332283	0.329499	0.492378	0.529342	0.351931	0.250112	0.698013	0.196168	0.915019	0.496164	0.523684
JUN	-0.013594	-0.033725	0.033703	0.165857	0.457091	0.567618	1.000000	0.741285	0.655142	0.551890	0.490393	0.229718	0.088782	0.891303	0.001016	0.538562	0.893968	0.409050
JUL	-0.016240	-0.051642	0.016235	0.097334	0.268097	0.332283	0.741285	1.000000	0.686662	0.513067	0.299221	0.042671	-0.019427	0.812279	-0.019157	0.313726	0.907723	0.190400
AUG	0.006442	0.011952	0.072159	0.135071	0.256168	0.329499	0.655142	0.686662	1.000000	0.497037	0.250600	0.017488	0.001648	0.759304	0.050918	0.318347	0.840352	0.156293
SEP	-0.006670	0.024289	0.080148	0.178904	0.382525	0.492378	0.551890	0.513067	0.497037	1.000000	0.384138	0.153465	0.109457	0.715135	0.062131	0.470032	0.701980	0.319832
OCT	0.002406	0.012374	-0.004581	0.086187	0.368886	0.529342	0.490393	0.299221	0.250600	0.384138	1.000000	0.477503	0.281172	0.587065	0.003743	0.468048	0.416350	0.862761
NOV	-0.018776	0.067281	-0.023413	0.008814	0.165642	0.351931	0.229718	0.042671	0.017488	0.153465	0.477503	1.000000	0.451407	0.308768	0.022885	0.272268	0.126338	0.808798
DEC	-0.019139	0.219701	0.132570	0.136328	0.132892	0.250112	0.088782	-0.019427	0.001648	0.109457	0.281172	0.451407	1.000000	0.207176	0.204848	0.228473	0.042440	0.606658
ANNUAL	-0.008044	0.105696	0.181563	0.322199	0.577573	0.698013	0.891303	0.812279	0.759304	0.715135	0.587065	0.308768	0.207176	1.000000	0.169710	0.696318	0.943661	0.529596
Jan-Feb	-0.044653	0.842390	0.863815	0.576366	0.340841	0.196168	0.001016	-0.019157	0.050918	0.062131	0.003743	0.022885	0.204848	0.169710	1.000000	0.368551	0.018126	0.064088
Mar-May	0.010637	0.242256	0.382620	0.642294	0.864172	0.915019	0.538562	0.313726	0.318347	0.470032	0.468048	0.272268	0.228473	0.696318	0.368551	1.000000	0.472508	0.449004
Jun-Sep	-0.009418	-0.022748	0.051066	0.162055	0.394859	0.496164	0.893968	0.907723	0.840352	0.701980	0.416350	0.126338	0.042440	0.943661	0.018126	0.472508	1.000000	0.310433
Oct-Dec	-0.010155	0.090932	0.021878	0.090108	0.321407	0.523684	0.409050	0.190400	0.156293	0.319832	0.862761	0.808798	0.606658	0.529596	0.064088	0.449004	0.310433	1.000000
dfb.corr()
JAN	FEB	MAR	APR	MAY	JUN	JUL	AUG	SEP	OCT	NOV	DEC	ANNUAL	Jan-Feb	Mar-May	Jun-Sep	Oct-Dec
JAN	1.000000	0.868628	0.688776	0.343254	0.154175	-0.030926	-0.007617	0.027202	0.014375	0.002580	0.114688	0.417925	0.163069	0.956722	0.342612	-0.003460	0.138793
FEB	0.868628	1.000000	0.899637	0.633236	0.394301	0.194324	0.141263	0.153355	0.211977	0.184534	0.099818	0.297311	0.381363	0.975217	0.610682	0.181203	0.197984
MAR	0.688776	0.899637	1.000000	0.838087	0.609177	0.362265	0.204693	0.171421	0.337046	0.336384	0.109066	0.226834	0.510856	0.835958	0.813439	0.280189	0.262642
APR	0.343254	0.633236	0.838087	1.000000	0.885394	0.630982	0.388887	0.299930	0.550991	0.586121	0.204731	0.157686	0.722081	0.525200	0.978128	0.494013	0.411320
MAY	0.154175	0.394301	0.609177	0.885394	1.000000	0.785813	0.520490	0.427825	0.690867	0.704970	0.253589	0.123735	0.826231	0.300433	0.951078	0.641871	0.483174
JUN	-0.030926	0.194324	0.362265	0.630982	0.785813	1.000000	0.880365	0.758769	0.805113	0.633108	0.127333	-0.049641	0.948150	0.100323	0.700861	0.933746	0.358595
JUL	-0.007617	0.141263	0.204693	0.388887	0.520490	0.880365	1.000000	0.930407	0.776188	0.371574	-0.058499	-0.167302	0.872591	0.079567	0.446976	0.975505	0.127013
AUG	0.027202	0.153355	0.171421	0.299930	0.427825	0.758769	0.930407	1.000000	0.795095	0.269149	-0.134928	-0.207788	0.804021	0.102217	0.361462	0.932928	0.036091
SEP	0.014375	0.211977	0.337046	0.550991	0.690867	0.805113	0.776188	0.795095	1.000000	0.553410	0.035335	-0.077087	0.870953	0.130920	0.618872	0.875960	0.275773
OCT	0.002580	0.184534	0.336384	0.586121	0.704970	0.633108	0.371574	0.269149	0.553410	1.000000	0.707371	0.456134	0.686947	0.109535	0.637905	0.481505	0.885581
NOV	0.114688	0.099818	0.109066	0.204731	0.253589	0.127333	-0.058499	-0.134928	0.035335	0.707371	1.000000	0.883429	0.225908	0.109840	0.224876	-0.007930	0.948733
DEC	0.417925	0.297311	0.226834	0.157686	0.123735	-0.049641	-0.167302	-0.207788	-0.077087	0.456134	0.883429	1.000000	0.102116	0.361244	0.166068	-0.136980	0.801381
ANNUAL	0.163069	0.381363	0.510856	0.722081	0.826231	0.948150	0.872591	0.804021	0.870953	0.686947	0.225908	0.102116	1.000000	0.296805	0.784244	0.936238	0.458319
Jan-Feb	0.956722	0.975217	0.835958	0.525200	0.300433	0.100323	0.079567	0.102217	0.130920	0.109535	0.109840	0.361244	0.296805	1.000000	0.511667	0.104882	0.178260
Mar-May	0.342612	0.610682	0.813439	0.978128	0.951078	0.700861	0.446976	0.361462	0.618872	0.637905	0.224876	0.166068	0.784244	0.511667	1.000000	0.561963	0.447262
Jun-Sep	-0.003460	0.181203	0.280189	0.494013	0.641871	0.933746	0.975505	0.932928	0.875960	0.481505	-0.007930	-0.136980	0.936238	0.104882	0.561963	1.000000	0.209174
Oct-Dec	0.138793	0.197984	0.262642	0.411320	0.483174	0.358595	0.127013	0.036091	0.275773	0.885581	0.948733	0.801381	0.458319	0.178260	0.447262	0.209174	1.000000
sns.heatmap(df.corr())

sns.heatmap(dfa.corr())

sns.heatmap(dfb.corr())

subs = dfa['SUBDIVISION'].unique()
print (subs)
print ('TOTAL SUBDIVISIONS: ', len(subs))
['ANDAMAN & NICOBAR ISLANDS' 'ARUNACHAL PRADESH' 'ASSAM & MEGHALAYA'
 'NAGA MANI MIZO TRIPURA' 'SUB HIMALAYAN WEST BENGAL & SIKKIM'
 'GANGETIC WEST BENGAL' 'ORISSA' 'JHARKHAND' 'BIHAR' 'EAST UTTAR PRADESH'
 'WEST UTTAR PRADESH' 'UTTARAKHAND' 'HARYANA DELHI & CHANDIGARH' 'PUNJAB'
 'HIMACHAL PRADESH' 'JAMMU & KASHMIR' 'WEST RAJASTHAN' 'EAST RAJASTHAN'
 'WEST MADHYA PRADESH' 'EAST MADHYA PRADESH' 'GUJARAT REGION'
 'SAURASHTRA & KUTCH' 'KONKAN & GOA' 'MADHYA MAHARASHTRA' 'MATATHWADA'
 'VIDARBHA' 'CHHATTISGARH' 'COASTAL ANDHRA PRADESH' 'TELANGANA'
 'RAYALSEEMA' 'TAMIL NADU' 'COASTAL KARNATAKA' 'NORTH INTERIOR KARNATAKA'
 'SOUTH INTERIOR KARNATAKA' 'KERALA' 'LAKSHADWEEP']
TOTAL SUBDIVISIONS:  36
unique_state_counts_yearwise = dfa.groupby(by='YEAR')[['SUBDIVISION']].count()['SUBDIVISION'].value_counts()

print (unique_state_counts_yearwise)
36    92
35    22
34     1
Name: SUBDIVISION, dtype: int64
state_count = dfa.groupby(by='SUBDIVISION')[['ANNUAL']].count().sort_values(by='ANNUAL')
print (state_count.head(10))
                           ANNUAL
SUBDIVISION                      
ARUNACHAL PRADESH              91
LAKSHADWEEP                   103
ANDAMAN & NICOBAR ISLANDS     104
COASTAL KARNATAKA             114
JAMMU & KASHMIR               114
WEST MADHYA PRADESH           114
VIDARBHA                      115
UTTARAKHAND                   115
TELANGANA                     115
TAMIL NADU                    115
overall = dfa.groupby(by='SUBDIVISION').sum()[['ANNUAL']].sort_values(by='ANNUAL', ascending=False)
overall.head()
ANNUAL
SUBDIVISION	
COASTAL KARNATAKA	388558.7
KONKAN & GOA	342433.9
KERALA	336431.1
SUB HIMALAYAN WEST BENGAL & SIKKIM	316505.0
ARUNACHAL PRADESH	311116.0
highest_sub = overall.index.values[0]
lowest_sub = overall.index.values[-1]
print ('Highest rain in: ', highest_sub)
print ('Lowest rain in: ', lowest_sub)
Highest rain in:  COASTAL KARNATAKA
Lowest rain in:  WEST RAJASTHAN
subs = dfb['DISTRICT'].unique()
print (subs)
print ('TOTAL DISTRICT: ', len(subs))
['NICOBAR' 'SOUTH ANDAMAN' 'N & M ANDAMAN' 'LOHIT' 'EAST SIANG'
 'SUBANSIRI F.D' 'TIRAP' 'ANJAW (LOHIT)' 'LOWER DIBANG' 'CHANGLANG'
 'PAPUM PARE' 'LOW SUBANSIRI' 'UPPER SIANG' 'WEST SIANG' 'DIBANG VALLEY'
 'WEST KAMENG' 'EAST KAMENG' 'TAWANG(W KAME' 'KURUNG KUMEY' 'CACHAR'
 'DARRANG' 'GOALPARA' 'KAMRUP' 'LAKHIMPUR' 'NORTH CACHAR' 'NAGAON'
 'SIVASAGAR' 'BARPETA' 'DHUBRI' 'DIBRUGARH' 'JORHAT' 'KARIMGANJ'
 'KOKRAJHAR' 'SHONITPUR' 'GOLAGHAT' 'TINSUKIA' 'HAILAKANDI'
 'DHEMAJI(LAKHI' 'KARBI ANGLONG' 'UDALGURI(DARA' 'KAMRUP METROP'
 'CHIRANG(BONGAI' 'BAKSA BARPETA' 'BONGAIGAON' 'MORIGAON' 'NALBARI'
 'EAST KHASI HI' 'JAINTIA HILLS' 'EAST GARO HIL' 'RI-BHOI' 'SOUTH GARO HI'
 'W KHASI HILL' 'WEST GARO HIL' 'IMPHAL EAST' 'SENAPATI' 'TAMENGLONG'
 'CHANDEL' 'UKHRUL' 'THOUBAL' 'BISHNUPUR' 'IMPHAL WEST' 'CHURACHANDPUR'
 'AIZAWL' 'CHAMPHAI' 'KOLASIB' 'LUNGLEI' 'CHHIMTUIPUI' 'LAWNGTLAI' 'MAMIT'
 'SAIHA' 'SERCHHIP' 'KOHIMA' 'TUENSANG' 'MOKOKCHUNG' 'DIMAPUR' 'WOKHA'
 'MON' 'ZUNHEBOTO' 'PHEK' 'KEPHRIE' 'LONGLENG' 'PEREN' 'NORTH TRIPURA'
 'SOUTH TRIPURA' 'WEST TRIPURA' 'DHALAI' 'COOCH BEHAR' 'DARJEELING'
 'JALPAIGURI' 'MALDA' 'SOUTH DINAJPUR' 'NORTH DINAJPUR' 'NORTH SIKKIM'
 'EAST SIKKIM' 'WEST SIKKIM' 'SOUTH SIKKIM' 'BANKURA' 'BIRBHUM' 'BURDWAN'
 'HOOGHLY' 'HOWRAH' 'PURULIA' 'MURSHIDABAD' 'NADIA' 'NORTH 24 PARG'
 'SOUTH 24 PARG' 'EAST MIDNAPOR' 'WEST MIDNAPOR' 'KOLKATA' 'BALASORE'
 'BOLANGIR' 'KANDHAMAL/PHU' 'CUTTACK' 'DHENKANAL' 'GANJAM' 'KALAHANDI'
 'KEONDJHARGARH' 'KORAPUT' 'MAYURBHANJ' 'PURI' 'SAMBALPUR' 'SUNDARGARH'
 'BHADRAK' 'JAJPUR' 'KENDRAPARA' 'ANGUL' 'NAWAPARA' 'MALKANGIRI'
 'NAWARANGPUR' 'NAYAGARH' 'KHURDA' 'BARGARH' 'JHARSUGUDA' 'DEOGARH'
 'RAYAGADA' 'GAJAPATI' 'JAGATSINGHAPU' 'BOUDHGARH' 'SONEPUR' 'BOKARO'
 'DHANBAD' 'DUMKA' 'HAZARIBAG' 'PALAMU' 'RANCHI' 'SAHIBGANJ'
 'WEST SINGHBHUM' 'DEOGHAR' 'GIRIDIH' 'GODDA' 'GUMLA' 'LOHARDAGA' 'CHATRA'
 'KODERMA' 'PAKUR' 'EAST SINGHBHU' 'GARHWA' 'SERAIKELA-KHA' 'JAMTARA'
 'LATEHAR' 'SIMDEGA' 'KHUNTI(RANCHI' 'RAMGARH' 'BHAGALPUR'
 'EAST CHAMPARAN' 'DARBHANGA' 'GAYA' 'MUNGER' 'MUZAFFARPUR'
 'WEST CHAMPARAN' 'PURNEA' 'GOPALGANJ' 'MADHUBANI' 'AURANGABAD'
 'BEGUSARAI' 'BHOJPUR' 'NALANDA' 'PATNA' 'KATIHAR' 'KHAGARIA' 'SARAN'
 'MADHEPURA' 'NAWADA' 'ROHTAS' 'SAMASTIPUR' 'SITAMARHI' 'SIWAN' 'VAISHALI'
 'JAHANABAD' 'BUXAR' 'ARARIA' 'BANKA' 'BHABUA' 'JAMUI' 'KISHANGANJ'
 'SHEIKHPURA' 'SUPAUL' 'LAKHISARAI' 'SHEOHAR' 'ARWAL' 'SAHARSA'
 'ALLAHABAD' 'AZAMGARH' 'BAHRAICH' 'BALLIA' 'BANDA' 'BARABANKI' 'BASTI'
 'DEORIA' 'FAIZABAD' 'FARRUKHABAD' 'FATEHPUR' 'GHAZIPUR' 'GONDA'
 'GORAKHPUR' 'HARDOI' 'JAUNPUR' 'KANPUR NAGAR' 'KHERI LAKHIMP' 'LUCKNOW'
 'MIRZAPUR' 'PRATAPGARH' 'RAE BARELI' 'SITAPUR' 'SULTANPUR' 'UNNAO'
 'VARANASI' 'SONBHADRA' 'MAHARAJGANJ' 'MAU' 'SIDDHARTH NGR' 'KUSHINAGAR'
 'AMBEDKAR NAGAR' 'KANNAUJ' 'BALRAMPUR' 'KAUSHAMBI' 'SAHUJI MAHARA'
 'KANPUR DEHAT' 'CHANDAULI' 'SANT KABIR NGR' 'SANT RAVIDAS'
 'SHRAVASTI NGR' 'AGRA' 'ALIGARH' 'BAREILLY' 'BIJNOR' 'BADAUN'
 'BULANDSHAHAR' 'ETAH' 'ETAWAH' 'HAMIRPUR' 'JALAUN' 'JHANSI' 'LALITPUR'
 'MAINPURI' 'MATHURA' 'MEERUT' 'MORADABAD' 'MUZAFFARNAGAR' 'PILIBHIT'
 'RAMPUR' 'SAHARANPUR' 'SHAHJAHANPUR' 'GHAZIABAD' 'FIROZABAD' 'MAHOBA'
 'MAHAMAYA NAGA' 'AURAIYA' 'BAGPAT' 'JYOTIBA PHULE' 'GAUTAM BUDDHA'
 'KANSHIRAM NAG' 'ALMORA' 'CHAMOLI' 'DEHRADUN' 'GARHWAL PAURI' 'NAINITAL'
 'PITHORAGARH' 'GARHWAL TEHRI' 'UTTARKASHI' 'HARIDWAR' 'CHAMPAWAT'
 'RUDRAPRAYAG' 'UDHAM SINGH N' 'BAGESHWAR' 'AMBALA' 'GURGAON' 'HISAR'
 'JIND' 'KARNAL' 'MAHENDRAGARH' 'ROHTAK' 'BHIWANI' 'FARIDABAD'
 'KURUKSHETRA' 'SIRSA' 'SONEPAT(RTK)' 'YAMUNANAGAR' 'KAITHAL' 'PANIPAT'
 'REWARI' 'FATEHABAD' 'JHAJJAR' 'PANCHKULA' 'MEWAT' 'PALWAL(FRD)'
 'CHANDIGARH' 'NEW DELHI' 'CENTRAL DELHI' 'EAST DELHI' 'NORTH DELHI'
 'NE DELHI' 'SW DELHI' 'NW DELHI' 'SOUTH DELHI' 'WEST DELHI' 'AMRITSAR'
 'BATHINDA' 'FEROZEPUR' 'GURDASPUR' 'HOSHIARPUR' 'JALANDHAR' 'KAPURTHALA'
 'LUDHIANA' 'PATIALA' 'RUPNAGAR' 'SANGRUR' 'FARIDKOT' 'MOGA' 'NAWANSHAHR'
 'FATEHGARH SAH' 'MUKTSAR' 'MANSA' 'BARNALA' 'SAS NAGAR(MGA)' 'TARN TARAN'
 'BILASPUR' 'CHAMBA' 'KANGRA' 'KINNAUR' 'KULLU' 'LAHUL & SPITI' 'MANDI'
 'SHIMLA' 'SIRMAUR' 'SOLAN' 'UNA' 'ANANTNAG' 'BARAMULLA' 'DODA' 'JAMMU'
 'KATHUA' 'LADAKH (LEH)' 'UDHAMPUR' 'BADGAM' 'KUPWARA' 'PULWAMA'
 'SRINAGAR' 'KARGIL' 'POONCH' 'RAJOURI' 'BANDIPORE' 'GANDERWAL'
 'KULGAM/(ANT)' 'SHOPAN' 'SAMBA' 'KISTWAR' 'REASI' 'RAMBAN(DDA)' 'BARMER'
 'BIKANER' 'CHURU' 'SRI GANGANAGA' 'JAISALMER' 'JALORE' 'JODHPUR' 'NAGAUR'
 'PALI' 'HANUMANGARH' 'AJMER' 'ALWAR' 'BANSWARA' 'BHARATPUR' 'BHILWARA'
 'BUNDI' 'CHITTORGARH' 'DUNGARPUR' 'JAIPUR' 'JHALAWAR' 'JHUNJHUNU' 'KOTA'
 'SAWAI MADHOPUR' 'SIKAR' 'SIROHI' 'TONK' 'UDAIPUR' 'DHOLPUR' 'BARAN'
 'DAUSA' 'RAJSAMAND' 'KARAULI' 'PRATAPGARH(CHT' 'BETUL' 'VIDISHA' 'BHIND'
 'DATIA' 'DEWAS' 'DHAR' 'GUNA' 'GWALIOR' 'HOSHANGABAD' 'INDORE' 'JHABUA'
 'MANDSAUR' 'MORENA' 'KHANDWA' 'KHARGONE' 'RAISEN' 'RAJGARH' 'RATLAM'
 'SEHORE' 'SHAJAPUR' 'SHIVPURI' 'UJJAIN' 'BHOPAL' 'HARDA' 'NEEMUCH'
 'SHEOPUR' 'BARWANI' 'ASHOKNAGAR(GNA' 'BURHANPUR' 'ALIRAJPUR(JBA)'
 'BALAGHAT' 'CHHATARPUR' 'CHHINDWARA' 'JABALPUR' 'MANDLA' 'NARSINGHPUR'
 'PANNA' 'REWA' 'SAGAR' 'SATNA' 'SEONI' 'SHAHDOL' 'SIDHI' 'TIKAMGARH'
 'KATNI' 'DINDORI' 'UMARIA' 'DAMOH' 'ANUPPUR(SHAHD' 'SINGRAULI'
 'AHMEDABAD' 'BANASKANTHA' 'BARODA' 'BHARUCH' 'VALSAD' 'DANGS' 'KHEDA'
 'MEHSANA' 'PANCHMAHALS' 'SABARKANTHA' 'SURAT' 'GANDHINAGAR'
 'NARMADA(BRC)' 'NAVSARI(VSD)' 'ANAND(KHR)' 'PATAN(MHSN)' 'DAHOD(PNML)'
 'TAPI(SRT)' 'AMRELI' 'BHAVNAGAR' 'JAMNAGAR' 'JUNAGADH' 'KUTCH' 'RAJKOT'
 'SURENDRANAGAR' 'PORBANDAR' 'DNH' 'DAMAN' 'DIU' 'MUMBAI CITY' 'RAIGAD'
 'RATNAGIRI' 'THANE' 'SINDHUDURG' 'MUMBAI SUB' 'NORTH GOA' 'SOUTH GOA'
 'AHMEDNAGAR' 'DHULE' 'JALGAON' 'KOLHAPUR' 'NASHIK' 'PUNE' 'SANGLI'
 'SATARA' 'SOLAPUR' 'NANDURBAR' 'BEED' 'NANDED' 'OSMANABAD' 'PARBHANI'
 'LATUR' 'JALNA' 'HINGOLI' 'AKOLA' 'AMRAVATI' 'BHANDARA' 'BULDHANA'
 'CHANDRAPUR' 'NAGPUR' 'YAVATMAL' 'WARDHA' 'GADCHIROLI' 'WASHIM' 'GONDIA'
 'BASTAR' 'DURG' 'RAIGARH' 'RAIPUR' 'SURGUJA' 'RAJNANDGAON' 'DANTEWADA'
 'KANKER (NORH' 'JANJGIR-CHAMP' 'KORBA' 'JASHPUR' 'DHAMTARI' 'MAHASAMUND'
 'KORIYA' 'KOWARDHA (KAB' 'NARAYANPUR' 'BIJAPUR' 'EAST GODAVARI'
 'WEST GODAVARI' 'GUNTUR' 'KRISHNA' 'NELLORE' 'PRAKASAM' 'SRIKAKULAM'
 'VISAKHAPATNAM' 'VIZIANAGARAM' 'ADILABAD' 'HYDERABAD' 'KARIMNAGAR'
 'KHAMMAM' 'MAHABUBNAGAR' 'MEDAK' 'NALGONDA' 'NIZAMABAD' 'WARANGAL'
 'RANGAREDDY' 'ANANTAPUR' 'CHITTOOR' 'KUDDAPAH' 'KURNOOL' 'VELLORE'
 'COIMBATORE' 'DHARMAPURI' 'KANYAKUMARI' 'CHENNAI' 'MADURAI' 'NILGIRIS'
 'RAMANATHAPURA' 'SALEM' 'THANJAVUR' 'TIRUCHIRAPPAL' 'TIRUNELVELI' 'ERODE'
 'PUDUKKOTTAI' 'DINDIGUL' 'VIRUDHUNAGAR' 'SIVAGANGA' 'THOOTHUKUDI'
 'TIRUVANNAMALA' 'NAGAPATTINAM' 'VILUPPURAM' 'CUDDALORE' 'KANCHIPURAM'
 'TIRUVALLUR' 'THENI' 'NAMAKKAL' 'KARUR' 'PERAMBALUR' 'TIRUVARUR'
 'KRISHNAGIRI' 'ARIYALUR' 'TIRUPUR' 'PONDICHERRY' 'KARAIKAL' 'MAHE'
 'YANAM' 'UTTAR KANNADA' 'DAKSHIN KANDA' 'UDUPI' 'BELGAM' 'BIDAR'
 'DHARWAD' 'GULBARGA' 'YADGIR' 'RAICHUR' 'BAGALKOTE' 'GADAG' 'HAVERI'
 'KOPPAL' 'BANGALORE RUR' 'BELLARY' 'CHIKMAGALUR' 'CHITRADURGA' 'KODAGU'
 'HASSAN' 'KOLAR' 'MANDYA' 'MYSORE' 'SHIMOGA' 'TUMKUR' 'BANGALORE URB'
 'CHAMARAJANAGA' 'DAVANGERE' 'RAMNAGAR(BNGR)' 'CHICKBALLAPUR' 'ALAPPUZHA'
 'CANNUR' 'ERNAKULAM' 'KOTTAYAM' 'KOZHIKODE' 'MALAPPURAM' 'PALAKKAD'
 'KOLLAM' 'THRISSUR' 'THIRUVANANTHA' 'IDUKKI' 'KASARGOD' 'PATHANAMTHITTA'
 'WAYANAD' 'LAKSHADWEEP']
TOTAL DISTRICT:  637
unique_state_counts_yearwise = dfb.groupby(by='ANNUAL')[['DISTRICT']].count()['DISTRICT'].value_counts()

print (unique_state_counts_yearwise)
1    553
2     33
3      3
9      1
4      1
Name: DISTRICT, dtype: int64
state_count = dfb.groupby(by='DISTRICT')[['ANNUAL']].count().sort_values(by='ANNUAL')
print (state_count.head(10))
               ANNUAL
DISTRICT             
ADILABAD            1
NEEMUCH             1
NELLORE             1
NEW DELHI           1
NICOBAR             1
NILGIRIS            1
NIZAMABAD           1
NORTH 24 PARG       1
NORTH CACHAR        1
NORTH DELHI         1
overall = dfb.groupby(by='DISTRICT').sum()[['ANNUAL']].sort_values(by='ANNUAL', ascending=False)
overall.head()
ANNUAL
DISTRICT	
TAMENGLONG	7229.3
JAINTIA HILLS	6379.9
EAST KHASI HI	6166.1
UPPER SIANG	4402.1
UDUPI	4306.0
highest_sub = overall.index.values[0]
lowest_sub = overall.index.values[-1]
print ('Highest rain in: ', highest_sub)
print ('Lowest rain in: ', lowest_sub)
Highest rain in:  TAMENGLONG
Lowest rain in:  LADAKH (LEH)